#!/bin/sh
#https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html
thisservice=keepalive.service

case "${1}" in
   upgrade)
      # This preinst is being run before an upgrade.
      # $2 is old-version-number
      systemctl stop keepalive.service 1>/dev/null 2>&1
      ;;
   install)
      # Brand new installation of the package.
      [ ]
      ;;
esac

exit 0
