#!/bin/sh
# deb pre 2017-01-26
#https://www.debian.org/doc/debian-policy/ch-maintainerscripts.html
thisservice=keepalive.service
{
case "${1}" in
   upgrade)
      # Upgrade. $2 is old-version-number.
      systemctl stop ${thiservice}
      ;;
   install)
      # New install.
      :
      ;;
esac
} 1>/dev/null 2>&1
exit 0
