#!/bin/sh

thisservice=keepalive.service

case "${1}" in
   upgrade)
      # This prerm upgrade is running because a newer version of this package is being installed.
      # $2 is new-version-number
      [ ]
      ;;
   remove)
      # No new package being installed. Just remove it.
      systemctl stop "${thisservice}" 1>/dev/null 2>&1
      systemctl disable "${thisservice}" 1>/dev/null 2>&1
      ;;
esac

exit 0 
